import type {
  User,
  BankAccount,
  BankMovement,
  Customer,
  Invoice,
  Expense,
  Task,
  KPI,
  HotelMetrics,
} from './types';

// === USUARIOS ===
export const mockUsers: User[] = [
  {
    id: '1',
    username: 'demo',
    name: 'Administrador',
    role: 'admin',
    email: '',
    phone: '',
  },
];

// Contraseña: demo / demo123
export const mockPasswords: Record<string, string> = {
  demo: 'demo123',
};

// === CUENTAS BANCARIAS ===
export const mockBankAccounts: BankAccount[] = [
  {
    id: '1',
    name: 'Cuenta Corriente Operacional',
    bank: 'Banco de Chile',
    accountNumber: '00-123-45678-90',
    balance: 45820000,
    currency: 'CLP',
    type: 'corriente',
  },
  {
    id: '2',
    name: 'Cuenta Vista POS',
    bank: 'Banco Estado',
    accountNumber: '98-765-43210-01',
    balance: 8950000,
    currency: 'CLP',
    type: 'vista',
  },
  {
    id: '3',
    name: 'Cuenta Ahorro Reserva',
    bank: 'Banco Santander',
    accountNumber: '55-444-33333-22',
    balance: 15000000,
    currency: 'CLP',
    type: 'ahorro',
  },
];

// === MOVIMIENTOS BANCARIOS ===
export const mockBankMovements: BankMovement[] = [
  {
    id: '1',
    accountId: '1',
    date: '2025-11-15',
    description: 'Depósito Booking.com - Reservas semana 46',
    amount: 3500000,
    type: 'ingreso',
    category: 'deposito',
    reconciled: true,
    reference: 'DEP-2025-1145',
  },
  {
    id: '2',
    accountId: '2',
    date: '2025-11-15',
    description: 'POS - Consumos restaurant',
    amount: 850000,
    type: 'ingreso',
    category: 'pos',
    reconciled: true,
  },
  {
    id: '3',
    accountId: '1',
    date: '2025-11-14',
    description: 'Transferencia Agencia Turismo Plus',
    amount: 2100000,
    type: 'ingreso',
    category: 'transferencia',
    reconciled: true,
    reference: 'TRF-AP-2025',
  },
  {
    id: '4',
    accountId: '1',
    date: '2025-11-14',
    description: 'Pago proveedor lavandería Industrial Clean',
    amount: 980000,
    type: 'egreso',
    category: 'transferencia',
    reconciled: false,
    reference: 'PAGO-IC-1101',
  },
  {
    id: '5',
    accountId: '2',
    date: '2025-11-13',
    description: 'Comisión bancaria POS',
    amount: 45000,
    type: 'egreso',
    category: 'comision',
    reconciled: true,
  },
  {
    id: '6',
    accountId: '1',
    date: '2025-11-13',
    description: 'Fee mantención cuenta corriente',
    amount: 12000,
    type: 'egreso',
    category: 'fee',
    reconciled: true,
  },
  {
    id: '7',
    accountId: '1',
    date: '2025-11-12',
    description: 'Depósito Expedia - Grupos corporativos',
    amount: 4200000,
    type: 'ingreso',
    category: 'deposito',
    reconciled: false,
    reference: 'DEP-EXP-4521',
  },
  {
    id: '8',
    accountId: '2',
    date: '2025-11-12',
    description: 'POS - Bar y minibar',
    amount: 320000,
    type: 'ingreso',
    category: 'pos',
    reconciled: true,
  },
];

// === CLIENTES ===
export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Booking.com',
    rut: '76.123.456-7',
    email: 'payments@booking.com',
    phone: '+1 800 BOOKING',
    address: 'Online Travel Agency',
    type: 'ota',
    contactPerson: 'Support Team',
  },
  {
    id: '2',
    name: 'Turismo Plus Ltda.',
    rut: '77.654.321-8',
    email: 'admin@turismoplus.cl',
    phone: '+56 9 8765 4321',
    address: 'Av. Providencia 1234, Santiago',
    type: 'agencia',
    contactPerson: 'Roberto Sánchez',
  },
  {
    id: '3',
    name: 'Expedia Group',
    rut: '78.987.654-3',
    email: 'partners@expedia.com',
    phone: '+1 800 EXPEDIA',
    address: 'Online Travel Agency',
    type: 'ota',
    contactPerson: 'Partner Services',
  },
  {
    id: '4',
    name: 'Empresa Minera del Norte S.A.',
    rut: '79.111.222-4',
    email: 'rrhh@mineranorte.cl',
    phone: '+56 2 2345 6789',
    address: 'Av. Apoquindo 5678, Las Condes',
    type: 'empresa',
    contactPerson: 'Patricia Rojas',
  },
  {
    id: '5',
    name: 'Eventos Corporativos SpA',
    rut: '80.333.444-5',
    email: 'ventas@eventoscorp.cl',
    phone: '+56 9 5555 6666',
    address: 'Av. Vitacura 9012, Vitacura',
    type: 'evento',
    contactPerson: 'Juan Pérez',
  },
];

// === FACTURAS ===
export const mockInvoices: Invoice[] = [
  {
    id: '1',
    number: 'F-00345-2025',
    customerId: '1',
    customerName: 'Booking.com',
    date: '2025-11-01',
    dueDate: '2025-11-30',
    amount: 3500000,
    status: 'pagada',
    paymentMethod: 'Transferencia',
    items: [
      {
        id: '1',
        description: 'Habitaciones Dobles - Semana 46',
        quantity: 28,
        unitPrice: 95000,
        total: 2660000,
        roomNights: 28,
      },
      {
        id: '2',
        description: 'Habitaciones Suite - Semana 46',
        quantity: 7,
        unitPrice: 120000,
        total: 840000,
        roomNights: 7,
      },
    ],
  },
  {
    id: '2',
    number: 'F-00346-2025',
    customerId: '2',
    customerName: 'Turismo Plus Ltda.',
    date: '2025-11-10',
    dueDate: '2025-12-10',
    amount: 2100000,
    status: 'pendiente',
    items: [
      {
        id: '3',
        description: 'Tour Group - 15 habitaciones x 2 noches',
        quantity: 30,
        unitPrice: 70000,
        total: 2100000,
        roomNights: 30,
      },
    ],
    notes: 'Convenio agencia - Descuento 15%',
  },
  {
    id: '3',
    number: 'F-00347-2025',
    customerId: '4',
    customerName: 'Empresa Minera del Norte S.A.',
    date: '2025-10-25',
    dueDate: '2025-11-25',
    amount: 5600000,
    status: 'vencida',
    items: [
      {
        id: '4',
        description: 'Alojamiento equipo ejecutivo - Octubre',
        quantity: 56,
        unitPrice: 100000,
        total: 5600000,
        roomNights: 56,
      },
    ],
    notes: 'Convenio corporativo - Factura mensual',
  },
  {
    id: '4',
    number: 'F-00348-2025',
    customerId: '5',
    customerName: 'Eventos Corporativos SpA',
    date: '2025-11-12',
    dueDate: '2025-12-12',
    amount: 7800000,
    status: 'pendiente',
    items: [
      {
        id: '5',
        description: 'Salones para conferencia - 3 días',
        quantity: 3,
        unitPrice: 1500000,
        total: 4500000,
      },
      {
        id: '6',
        description: 'Coffee breaks y almuerzos - 120 personas',
        quantity: 120,
        unitPrice: 25000,
        total: 3000000,
      },
      {
        id: '7',
        description: 'Habitaciones ejecutivos',
        quantity: 10,
        unitPrice: 130000,
        total: 300000,
        roomNights: 10,
      },
    ],
  },
];

// === GASTOS ===
export const mockExpenses: Expense[] = [
  {
    id: '1',
    date: '2025-11-14',
    description: 'Reparación sistema aire acondicionado piso 3',
    amount: 850000,
    category: 'mantenimiento',
    status: 'aprobado',
    createdBy: 'Carlos Administrador',
    supplier: 'Climatización Express',
    invoiceNumber: 'CE-4521',
  },
  {
    id: '2',
    date: '2025-11-12',
    description: 'Compra productos limpieza y amenities',
    amount: 680000,
    category: 'housekeeping',
    status: 'pagado',
    createdBy: 'María Contadora',
    supplier: 'Distribuidora Hotelera S.A.',
    invoiceNumber: 'DH-7845',
  },
  {
    id: '3',
    date: '2025-11-10',
    description: 'Insumos restaurant y bar - Noviembre',
    amount: 2340000,
    category: 'f&b',
    status: 'aprobado',
    createdBy: 'Carlos Administrador',
    supplier: 'Supermercado Mayorista',
    invoiceNumber: 'SM-9632',
  },
  {
    id: '4',
    date: '2025-11-08',
    description: 'Servicio lavandería externa - Octubre',
    amount: 980000,
    category: 'lavanderia',
    status: 'pendiente',
    createdBy: 'María Contadora',
    supplier: 'Industrial Clean',
    invoiceNumber: 'IC-1101',
  },
  {
    id: '5',
    date: '2025-11-15',
    description: 'Bonos desempeño personal housekeeping',
    amount: 450000,
    category: 'rrhh',
    status: 'aprobado',
    createdBy: 'Carlos Administrador',
  },
  {
    id: '6',
    date: '2025-11-05',
    description: 'Luz, agua y gas - Octubre',
    amount: 1250000,
    category: 'servicios-basicos',
    status: 'pagado',
    createdBy: 'María Contadora',
  },
  {
    id: '7',
    date: '2025-11-03',
    description: 'Campaña Google Ads - Temporada alta',
    amount: 580000,
    category: 'marketing',
    status: 'pagado',
    createdBy: 'Carlos Administrador',
    supplier: 'Agencia Digital Pro',
  },
  {
    id: '8',
    date: '2025-11-01',
    description: 'Licencias software PMS y gestión',
    amount: 320000,
    category: 'tecnologia',
    status: 'pagado',
    createdBy: 'María Contadora',
    supplier: 'HotelTech Solutions',
  },
];

// === TAREAS ===
export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Auditoría nocturna - Cierre contable',
    description: 'Revisar cierre de caja y conciliación de ventas del día',
    dueDate: '2025-11-17',
    priority: 'alta',
    status: 'pendiente',
    assignedTo: 'María Contadora',
    createdAt: '2025-11-16',
    category: 'auditoria',
  },
  {
    id: '2',
    title: 'Conciliar cuentas bancarias - Semana 46',
    description: 'Realizar conciliación de las 3 cuentas bancarias',
    dueDate: '2025-11-20',
    priority: 'alta',
    status: 'en-progreso',
    assignedTo: 'María Contadora',
    createdAt: '2025-11-15',
    category: 'conciliacion',
  },
  {
    id: '3',
    title: 'Preparar reporte mensual gerencia',
    description: 'Generar ADR, RevPAR, GOP y ocupación de noviembre',
    dueDate: '2025-11-30',
    priority: 'alta',
    status: 'pendiente',
    assignedTo: 'Carlos Administrador',
    createdAt: '2025-11-16',
    category: 'reporte',
  },
  {
    id: '4',
    title: 'Pago proveedores - Vencimiento 25/11',
    description: 'Procesar pagos de lavandería, limpieza y mantenimiento',
    dueDate: '2025-11-25',
    priority: 'media',
    status: 'pendiente',
    assignedTo: 'María Contadora',
    createdAt: '2025-11-16',
    category: 'pago',
  },
  {
    id: '5',
    title: 'Seguimiento facturas vencidas',
    description: 'Contactar Empresa Minera del Norte por factura octubre',
    dueDate: '2025-11-18',
    priority: 'alta',
    status: 'pendiente',
    assignedTo: 'Carlos Administrador',
    createdAt: '2025-11-16',
    category: 'vencimiento',
  },
  {
    id: '6',
    title: 'Renovar seguros del hotel',
    description: 'Vencimiento póliza de seguros - Revisar y renovar',
    dueDate: '2025-11-30',
    priority: 'media',
    status: 'pendiente',
    assignedTo: 'Carlos Administrador',
    createdAt: '2025-11-10',
    category: 'vencimiento',
  },
];

// === KPIs ===
export const mockKPIs: KPI[] = [
  {
    id: '1',
    name: 'ADR (Tarifa Promedio)',
    value: 95000,
    change: 8.5,
    period: 'Noviembre 2025',
    format: 'currency',
  },
  {
    id: '2',
    name: 'RevPAR',
    value: 76000,
    change: 12.3,
    period: 'Noviembre 2025',
    format: 'currency',
  },
  {
    id: '3',
    name: 'Ocupación',
    value: 80,
    change: 5.2,
    period: 'Noviembre 2025',
    format: 'percentage',
  },
  {
    id: '4',
    name: 'GOP (Utilidad Operativa)',
    value: 18500000,
    change: 15.8,
    period: 'Noviembre 2025',
    format: 'currency',
  },
];

// === MÉTRICAS DEL HOTEL ===
export const mockHotelMetrics: HotelMetrics = {
  adr: 95000,
  revpar: 76000,
  occupancy: 80,
  gop: 18500000,
  roomsAvailable: 50,
  roomsSold: 40,
  totalRevenue: 32450000,
  totalExpenses: 13950000,
};
